author: Steven Sherry

module: SwiftyTesseract
module_version: 3.0.0
github_url: https://github.com/SwiftyTesseract/SwiftyTesseract

theme: fullwidth
clean: true
readme: Readme.md
undocumented_text: ""
hide_documentation_coverage: true

xcodebuild_arguments: [ -project
                      , SwiftyTesseract/SwiftyTesseract.xcodeproj
                      , -scheme
                      , SwiftyTesseract
                      , -sdk
                      , iphonesimulator13.4
                      , -destination
                      , 'platform=iOS Simulator,name=iPhone 11,OS=13.4'
                      ]
