osx_image: xcode10
language: objective-c
cache: cocoapods
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
script:
- set -o pipefail && xcodebuild test -project SwiftyTesseract/SwiftyTesseract.xcodeproj -scheme SwiftyTesseractTests -sdk iphonesimulator11.3 -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod spec lint